from controleTarefas.serializers.serializerAlunos import AlunosSerializer
from controleTarefas.serializers.serializerDisciplinas import DisciplinaSerializer
from controleTarefas.serializers.serializerTarefas import SerializerTarefas
